### ISSUE TITLE
Im trying to figure out how you can make a player glow.

### ISSUE THREAD

**Issue by DualByte** [designer1337/csgo-cheat-base#40]
I have made it so that it does a for loop to run the same code on every player. I have set that variable entity is a player_t. How could I make the player glow?

**Comment by vxvvxv** [comment]
not to sound rude but you're obviously clueless on what you are doing so, i suggest learning the basics of game hacking before you even continue. you're spamming github issues because you lack the intellect and the intuition to do things yourself and wish to be hand held, we are not here to do that. that being said, guidedhacking has a good series of tutorials on basically everything already (omg yes including glow!) that's probably your best bet, although they do require you to invest your time into actually learning the language you are writing it in so, i don't think you will get very far, i hope you can prove me wrong and are able to show me a somewhat decent understanding of the language you choose and your self coded glow one day, good luck.

**Comment by DualByte** [comment]
Well the base doesn't have any documentation so it is very hard to do. I'm semi new to internal cheating. I found it easier to just write an esp than a glow hack because as I said there is no documentation.

**Comment by DualByte** [comment]
I was just about to close this because I got the glow to work. I had to read the source of the base(what I should have done in the first place). For anyone thinking how do I make or get a player to glow?
Do a for loop like this `for(int i = 0; i < interfaces::glow_manager->size; i++)`
After that you can get the glow object by doing `glow_object_definition_t& glowObject = interfaces::glow_manager->objects[i];`
Now you can change the glow object's settings using the glowObject variable.
