### ISSUE TITLE
How can I implement imgui to this? Not an issue but help would be nice

### ISSUE THREAD

**Issue by 3choN3wson** [designer1337/csgo-cheat-base#65]
Since there are no user interface libraries for csgo's surface I would like to use imgui but I cant find any directx hooks because there are no directx hooks. So I would like know is it even possible to implement imgui to this base?

**Comment by sowwe** [comment]
https://github.com/ChoZenTime/csgo-cheat-pasted-by-choZen

**Comment by bruhmoment21** [comment]
https://github.com/bruhmoment21/csgo-imgui-sdk
go full c+p

**Comment by VortexShrimp** [comment]
1. Hook EndScene or Present
2. Include and initialize ImGui
3. Hook WndProc so that ImGui gets keyboard/mouse input
4. Draw Window in EndScene
5. Hook Reset and reset objects and stuff
6. Profit????

Here is a good tutorial -> [Drawing an menu for your csgo internal hack](https://www.unknowncheats.me/forum/counterstrike-global-offensive/263391-drawing-menu-csgo-internal-hack.html)

You will need some idea of how to code in c++, some experience with ImGui and some knowledge of how to use an SDK or else you aren't going to be very successful in implementing ImGui. Also, look at the d3dx9 win32 [example](https://github.com/ocornut/imgui/blob/master/examples/example_win32_directx9/main.cpp) and understand how it works.

Good luck.
